<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$urlHelper = $this->plugin('url');
?>
<div id="user-bar">
<?php if ($user): ?>
	<div class="user-links">
	    <span class="user-id">
	        <?php
	        $url = $urlHelper('admin/id', ['controller' => 'user', 'id' => $user->getId()]);
	        //echo sprintf($translate('Signed in as %s'), $hyperlink($user->getName(), $url));
	        echo sprintf('%s', $hyperlink($user->getName(), $url));
	        ?>
	    </span>
        <?php echo $hyperlink($translate('Logout'), $urlHelper('logout'), ['class' => 'logout']); ?>
	</div>
<?php else: ?>
    <?php echo $hyperlink($translate('Log in'), $urlHelper('login'), ['class' => 'login']); ?>
<?php endif; ?>
</div>
