<?php

$site = $this->vars('site');
$translate = $this->plugin('translate');
$props = $this->pageProps();
$props['site']=$site;
$urls = $this->pageUrls($props,null,"arbre");

?>

<style> /* set the CSS */
    
.node circle {
  fill: #fff;
  stroke: steelblue;
  stroke-width: 3px;
}

.node text { font: 12px sans-serif; }

.node--internal text {
  text-shadow: 0 1px 0 #fff, 0 -1px 0 #fff, 1px 0 0 #fff, -1px 0 0 #fff;
}

.link {
  fill: none;
  stroke: #ccc;
  stroke-width: 2px;
}

</style>
<section class="hero-section">               
  <div id="cartoArbre"></div>
</section>

<script>


var container,width;
$(function() {
    showArbre();

});
function showArbre(){
    container = d3.select(".container");
    width = container.node().clientWidth;
    height= window.innerHeight - container.node().clientHeight;

    d3.select("#cartoArbre").select('svg').remove();
    d3.select('#cartoArbre').style('display','block');
    var r = new arbre({'idCont':'cartoArbre','width':width,'height':height
                    ,'dataUrl':"<?php echo $urls['getDataArbre'];?>"
                });
}

</script>
