<footer class="footer-section" style="background-color:#37A2B5;">
    <div class="footer__text" style="margin-top: -100px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="footer__text-widget">
                        <h5>Polemika</h5>
                        <!--<div class="footer__logo">
                                        <a href="/">Polemika</a>
                                        </div>-->
                        <p>Polemika est Génération automatique Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                            sed do eiusmod tempor incididunt
                            ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida viverra maecen
                            lacus vel facilisis.
                        </p>
                        <!--<div class="footer__social">
                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                        <a href="#"><i class="fa fa-youtube-play"></i></a>
                                        <a href="#"><i class="fa fa-instagram"></i></a>
                                        </div>-->
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="footer__text-widget">
                        <h5>ils nous soutiennent</h5>
                        <ul>
                            <li><a target="_blank" href="http://eur-artec.fr/"><img style="height: 50px;"
                                        src="<?php echo $this->assetUrl('images/logos/ArTeC.png'); ?>"
                                        alt="Artec" /></a></li>
                            <li><a target="_blank" href="https://www.iledefrance.fr/"><img style="height: 50px;"
                                        src="<?php echo $this->assetUrl('images/logos/region_ile-de-france.svg'); ?>"
                                        alt="Région Ile de France" /></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="footer__text-widget">
                        <h5>nous contacter</h5>
                        <ul class="footer__widget-info">
                            <li>
                                <span style="color:white;" class="fa fa-map-marker"></span>
                                Lorem ipsum ...
                            </li>
                            <li>
                                <span class="icon_chat_alt"></span>
                                Lorem ipsum ...
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer__text-copyright">
                <p style="color: #2a2163; font-size: 10px">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy; 2020 All rights reserved | This template is made by <a style="color: #2a2163;"
                        href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>