<?php
$userBar = $this->userBar();

?>
<div class="header__info">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8">
                <div class="header__info-left">
                    <ul>
                        <li><a target="_blank" href="https://www.univ-paris8.fr/EA-349-Laboratoire-Paragraphe">
                        <img style="height: 40px;" src="<?php echo $this->assetUrl('images/logos/logo-paragraphe-blanc.svg'); ?>" alt="Laboratoire Paragraphe" />
                        </a></li>
                        <li>
                            <a target="_blank" href="https://www.univ-paris8.fr/">
                            <img style="height: 40px;" src="<?php echo $this->assetUrl('images/logos/logo-p8-white.svg'); ?>" alt="Université Paris 8" />	                            		
                            </a>
                        </li>
                        <li><a target="_blank" href="http://eur-artec.fr/"><img style="height: 40px;"
                                        src="<?php echo $this->assetUrl('images/logos/ArTeC.png'); ?>"
                                        alt="Artec" /></a></li>
                        <li><a target="_blank" href="https://www.iledefrance.fr/"><img style="height: 40px;"
                                    src="<?php echo $this->assetUrl('images/logos/region_ile-de-france.svg'); ?>"
                                    alt="Région Ile de France" /></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-4">
                <div class="header__info-right">
                    <?php echo $userBar;?>
                </div>
            </div>
        </div>
    </div>
</div>

