<div class="mc-modal">
	<!-- Modal content -->
	<div class="mc-modal-content">
		<div class="mc-modal-header">
			<span class="close">
			&times;
			</span>
			<div class="mc-modal-title">
				Modal Header
			</div>
		</div>
		<div class="sep"></div>
		<div class="mc-modal-body">
			<p>
				Some text in the Modal Body
			</p>
			<p>
				Some other text...
			</p>
		</div>
		<div class="sep"></div>
		<div class="mc-modal-footer flex_layout" style="display: flex;">
			<div class="buttons" style="margin-left: auto !important;"></div>
		</div>
	</div>
</div>
