
<!-- Fenêtre modale pour le temps de chargement -->
<div class="modal fade" id="modWait" tabindex="-1" role="dialog" aria-labelledby="modWaitLbl" aria-hidden="true">
        <div class="modal-dialog modal-full" role="document">
                <div class="modal-content">
                <div class="modal-header">
                        <h5 class="modal-title" id="modWaitLbl">Merci de patienter...</h5>
                </div>
                <div class="modal-body" style="height: 180px;">
                        <div id="waitloader" style="display:block;"></div>
                        <div id="waitError" style="height: 100px;overflow:scroll;" ></div>
                </div>
                <div class="modal-footer">
                        <button id="waitFermer" type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                </div>
                </div>
        </div>
</div>
