<?php
    $user = $this->identity();

    $site = $this->vars('site');
    $nav = $site->publicNav();
    $container = $nav->getContainer();
    $activePage = $nav->findActive($container);
    $flux = $activePage['page']->label;    
    $translate = $this->plugin('translate');
    $props = $this->pageProps();
    $props['site']=$site;
    $urls = $this->pageUrls($props,null,$flux);

    //récupère l'action de la page
    $item = $this->api()->read('items', 6564)->getContent();
    $media = $item->media();
    
    //récupère le crible de l'action
    $oCrible = $item->value('jdc:hasCrible')->valueResource();
    $crible = $this->CribleFactory("",$oCrible);

    //récupère les items de la collection
    $oCollection = $item->value('schema:targetCollection')->valueResource();
    $itemsCollection = $this->api()->search('items', ['item_set_id'=>$oCollection->id()])->getContent();
?>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <section class="hero-section">               
        <div class="container information">
            <div class="row" >
                <div id='colGauche' class="col-lg-6 col-md-12">
                <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <?php foreach($media as $i=>$m): ?>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="<?php echo $i; ?>" class="<?php echo $i==0 ? "active" : ""; ?>" aria-current="true" aria-label="<?php echo "Image ".($i+1); ?>"></button>
    <?php endforeach; ?>
  </div>

  <div class="carousel-inner">
  <?php foreach($media as $i=>$m): ?>
    <div class="carousel-item <?php echo $i==0 ? "active" : ""; ?>">
      <img src="<?php echo $m->thumbnailUrl('square');?>" class="d-block w-100" alt="<?php echo $m->displayTitle();?>">
      <div class="carousel-caption d-none d-md-block">
        <h5><?php echo $item->displayTitle();?></h5>
        <p><?php echo $m->displayTitle();?></p>
      </div>
    </div>
    <?php endforeach; ?>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"  data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"  data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
                </div>
                <div id='colTxt' class="col-lg-6 col-md-12">
                    <div id='prgTxt'></div>
                    <div class="ui-widget" id='acChercheConcept' style="display: none;">
                        <label for="mondes" style="float: left;color:white;">Saisir un concept : </label>
                        <div id="spin-cartes" style="display: none;"
                                class="spinner-border spinner-border-sm"
                                role="status">
                                <span class="sr-only">Chargement...</span>
                        </div>
                        <input class="form-control" style="float: left;width:70%;height: 24px;" id="chercheConcept" >
                    </div>

                </div>
            </div>
        </div>
    </section>

<script src="<?php echo $this->assetUrl('js/d3.V6.min.js');?>"></script>

<script>


</script>  
<?php echo $this->partial('polemika/modal-wait');?>
