<?php

$site = $this->vars('site');
$translate = $this->plugin('translate');

?>

<section class="hero-section">               
<div class="hero__slider owl-carousel">
    <div class="hero__item set-bg" data-setbg="<?php echo $this->assetUrl('images/hero/hero-1.png'); ?>">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="hero__text">
                        <h5>Eduquer à l'esprit critique avec l'IA</h5>
                        <h2>Les olympiades de l'argumentation</h2>
                        <a href="<?php echo $site->siteUrl()."/page/qualification";?>" class="primary-btn">commencer maintenant</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="hero__img">
                        <img src="<?php echo $this->assetUrl('images/hero/hero-right.png'); ?>" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</section>
<!-- Hero Section End -->
<!-- Footer Section Begin -->
<?php echo $this->partial('polemika/footer');?>
